<?php

namespace Okapi\Aop\Service\Cache;

use Okapi\CodeTransformer\Service\Cache\CachePaths as CodeTransformerCachePaths;

/**
 * # Cache Paths
 *
 * The `CachePaths` class is responsible for generating the cache paths for
 * the different types of files that are generated by the AOP library.
 */
class CachePaths extends CodeTransformerCachePaths
{
    /**
     * # Directory of the proxies.
     *
     * This directory creates an exact copy of the original file structure.
     *
     * The weaved class will be included at the bottom of the file.
     *
     * @var string
     */
    private string $proxyDir = 'proxies';

    /**
     * # Directory of the weaving files.
     *
     * This directory creates an exact copy of the original file structure.
     *
     * The weaving file will include the join-points for the advices.
     */
    private string $weavingDir = 'weaving';

    /**
     * Proxied suffix for the proxied classes.
     *
     * @var string
     */
    public string $proxiedSuffix = '__AopProxied';

    /**
     * Get the file path for a proxied file.
     *
     * @param string $filePath
     *
     * @return string
     */
    public function getProxyCachePath(string $filePath): string
    {
        return $this->appendToCachePath($filePath, $this->proxyDir);
    }

    /**
     * Get the file path for a weaving file.
     *
     * @param string $filePath
     *
     * @return string
     */
    public function getWeavingCachePath(string $filePath): string
    {
        return $this->appendToCachePath($filePath, $this->weavingDir);
    }
}
