<?php

namespace Okapi\Aop\Core\Cache;

use Okapi\CodeTransformer\Core\Cache\CachePaths as CodeTransformerCachePaths;

/**
 * # Cache Paths
 *
 * This class is responsible for generating the cache paths for
 * the different types of files that are generated by the AOP library.
 */
class CachePaths extends CodeTransformerCachePaths
{
    /**
     * # Directory of the proxies.
     *
     * This directory creates an exact copy of the original file structure.
     *
     * The weaved class will be included at the bottom of the file.
     *
     * @var string
     */
    private string $proxyDir = 'proxies';

    /**
     * # Directory of the woven files.
     *
     * This directory creates an exact copy of the original file structure.
     *
     * The woven file will include the join-points for the advices.
     */
    private string $wovenDir = 'woven';

    /**
     * Proxied suffix for the proxied classes.
     *
     * @var string
     */
    public const PROXIED_SUFFIX = '__AopProxied';

    /**
     * Get the file path for a proxied file.
     *
     * @param string $filePath
     *
     * @return string
     */
    public function getProxyCachePath(string $filePath): string
    {
        return $this->appendToCachePath($filePath, $this->proxyDir);
    }

    /**
     * Get the file path for a woven file.
     *
     * @param string $filePath
     *
     * @return string
     */
    public function getWovenCachePath(string $filePath): string
    {
        return $this->appendToCachePath($filePath, $this->wovenDir);
    }
}
